Deploy/objects/Inscricao__c.object
<CustomObject>
    <description>Registra as inscrições nos treinamentos</description>
    <label>Inscrição</label>
    <nameField>
        <displayFormat>ins-{00000}</displayFormat>
        <label>Inscricao Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inscrições</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Ativo__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Define o status da inscrição</description>
        <inlineHelpText>Informe o status da inscrição</inlineHelpText>
        <label>Ativo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TreinamentoModuloId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Treinamento/Modulo inscrito</description>
        <inlineHelpText>Defina seu treinamento/modulo</inlineHelpText>
        <label>Treinamento Modulo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Ativo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Treinamento_Modulo__c</referenceTo>
        <relationshipLabel>Inscrições</relationshipLabel>
        <relationshipName>Inscricoes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Usuário inscrito</description>
        <inlineHelpText>Defina seu nome de usuário</inlineHelpText>
        <label>Inscrito</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Inscricoes</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Deploy/objects/Modulo__c.object
<CustomObject>
    <description>Exemplo:
Flow builder
Process builder
Apex code
Aura components
LWC components</description>
    <label>Modulo</label>
    <nameField>
        <label>Modulo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modulos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Ativo__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Define o status do modulo</description>
        <inlineHelpText>Informe status do modulo</inlineHelpText>
        <label>Ativo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Carga_Horaria__c</fullName>
        <description>Carga horaria prevista</description>
        <inlineHelpText>Informe a carga horaria prevista</inlineHelpText>
        <label>Carga Horaria</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Descricao__c</fullName>
        <description>Descrição do modulo</description>
        <inlineHelpText>Informe a descrição do modulo</inlineHelpText>
        <label>Descrição</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
</CustomObject>

Deploy/objects/Treinamento__c.object
<CustomObject>
    <description>Objeto de treinamentos realizados

Exemplos
Desenvolvimento declarativo
Desenvolvimento back-end
Desenvolvimento front-end</description>
    <label>Treinamento</label>
    <nameField>
        <label>Treinamento Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Treinamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Ativo__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Define o status do treinamento</description>
        <inlineHelpText>Informe status do treinamento</inlineHelpText>
        <label>Ativo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Descricao__c</fullName>
        <description>Descrição longa do treinamento</description>
        <inlineHelpText>Informe a descrição do treinamento</inlineHelpText>
        <label>Descrição</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Instrutor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Instrutor do curso</description>
        <inlineHelpText>Informe o nome instrutor do curso</inlineHelpText>
        <label>Instrutor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Treinamentos</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

Deploy/objects/Treinamento_Modulo__c.object
<CustomObject>
    <description>Treinamentos e Modulos</description>
    <gender/>
    <label>Treinamento Modulo</label>
    <nameField>
        <displayFormat>trm-{00000}</displayFormat>
        <label>Treinamento Modulo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treinamento Modulos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Ativo__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Define o status da junção</description>
        <inlineHelpText>Informe o status desta junção</inlineHelpText>
        <label>Ativo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ModuloId__c</fullName>
        <description>Modulo</description>
        <inlineHelpText>Defina o módulo a ser vinculado</inlineHelpText>
        <label>Modulo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Modulo__c.Ativo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Modulo__c</referenceTo>
        <relationshipLabel>Treinamento Modulos</relationshipLabel>
        <relationshipName>Treinamento_Modulos</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TreinamentoId__c</fullName>
        <description>Treinamento</description>
        <inlineHelpText>Defina o treinamento a ser vinculado</inlineHelpText>
        <label>Treinamento</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Treinamento__c.Ativo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Treinamento__c</referenceTo>
        <relationshipLabel>Treinamento Modulos</relationshipLabel>
        <relationshipName>Treinamento_Modulos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

force-app/main/default/classes/InscricaoController_Test.cls
@isTest
public class InscricaoController_Test {
    @testSetup
    private static void setLoadTestData(){
        List<Treinamento__c> mockupTreinamento = new List<Treinamento__c>();
        List<Modulo__c> mockupModulo = new List<Modulo__c>();
        List<Treinamento_Modulo__c> mockupTreinaModulo = new List<Treinamento_Modulo__c>();
        List<Inscricao__c> mockupInsc = new List<Inscricao__c>();
        Id IdUsuario = UserInfo.getUserId();
        List<Treinamento__c> MocupData1 = TestDataFactory.LoadTreinamento();
        List<Modulo__c> MocupData2 = TestDataFactory.LoadModulo();

        for(Treinamento__c objRow : MocupData1){

            mockupTreinamento.add(
                new Treinamento__c(Name = objRow.Descricao__c,Descricao__c = objRow.Descricao__c + ' Mockup',Instrutor__c = IdUsuario, Ativo__c = true)
            );
        }

        for(Modulo__c objRow : MocupData2){
            // Modulo
            mockupModulo.add(new Modulo__c(Name = objRow.Descricao__c, Descricao__c = objRow.Descricao__c + ' Mockup', Carga_Horaria__c = 4, Ativo__c = true)
            );
        }
        insert mockupTreinamento;
        insert mockupModulo;
        // Treinamento Modulo
        mockupTreinaModulo.add ( new Treinamento_Modulo__c(Ativo__c = true, TreinamentoId__c = mockupTreinamento[0].id, ModuloId__c = mockupModulo[0].id));
        insert mockupTreinaModulo;
        // Inscrição
        mockupInsc.add(new Inscricao__c(Ativo__c = true,UserId__c = IdUsuario,TreinamentoModuloId__c = mockupTreinaModulo[0].id));
        insert mockupInsc;
    }

    @isTest static void queryWithoutParameters() {
        string userName = '';
        List <sObject> objTest = InscricaoController.getInscricaoPorUsuario(userName);
        System.assertEquals(0,objTest.size());
    }

    static testmethod void queryWithParameters(){
        string userName = UserInfo.getName();
        List <sObject> objTest = InscricaoController.getInscricaoPorUsuario(userName);
        System.assertEquals(1,objTest.size());
    }

    @isTest static void TestTreinamentoModuloTrigger() {
        List<Treinamento_Modulo__c> objInsert = new List<Treinamento_Modulo__c>();
        
        List<Treinamento_Modulo__c> objCadastrado = [   SELECT Ativo__c , TreinamentoId__c , ModuloId__c
                                                        FROM Treinamento_Modulo__c LIMIT 1];
        
        for(Treinamento_Modulo__c objRow : objCadastrado){
            objInsert.add(
                new Treinamento_Modulo__c(
                    Ativo__c = objRow.Ativo__c, TreinamentoId__c = objRow.TreinamentoId__c, ModuloId__c= objRow.ModuloId__c
                )
            );
        }

        Test.startTest();
        // Como o registro já está na base deverá ocorrer o erro
        Database.SaveResult[] objResult = Database.insert(objInsert, false);
        Test.stopTest();

        // E verificamos os resultados
        System.assert(!objResult[0].isSuccess());
        System.assert(objResult[0].getErrors().size() > 0);
        System.assertEquals('Informação já cadastrada', objResult[0].getErrors()[0].getMessage());
    }


}