Deploy/objects/Modulo__c.object
<CustomObject>
    <description>Exemplo:
Flow builder
Process builder
Apex code
Aura components
LWC components</description>
    <label>Modulo</label>
    <nameField>
        <label>Modulo Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modulos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Ativo__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Define o status do modulo</description>
        <inlineHelpText>Informe status do modulo</inlineHelpText>
        <label>Ativo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Descricao__c</fullName>
        <description>Descrição do modulo</description>
        <inlineHelpText>Informe a descrição do modulo</inlineHelpText>
        <label>Descrição</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
</CustomObject>

Deploy/objects/Treinamento_Modulo__c.object
<CustomObject>
    <description>Treinamentos e Modulos</description>
    <gender/>
    <label>Treinamento Modulo</label>
    <nameField>
        <displayFormat>trm-{00000}</displayFormat>
        <label>Treinamento Modulo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treinamento Modulos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>Ativo__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Define o status da junção</description>
        <inlineHelpText>Informe o status desta junção</inlineHelpText>
        <label>Ativo</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ModuloId__c</fullName>
        <description>Modulo</description>
        <inlineHelpText>Defina o módulo a ser vinculado</inlineHelpText>
        <label>Modulo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Modulo__c.Ativo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Modulo__c</referenceTo>
        <relationshipLabel>Treinamento Modulos</relationshipLabel>
        <relationshipName>Treinamento_Modulos</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TreinamentoId__c</fullName>
        <description>Treinamento</description>
        <inlineHelpText>Defina o treinamento a ser vinculado</inlineHelpText>
        <label>Treinamento</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Treinamento__c.Ativo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Treinamento__c</referenceTo>
        <relationshipLabel>Treinamento Modulos</relationshipLabel>
        <relationshipName>Treinamento_Modulos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

Deploy/classes/ModuloController.cls
public with sharing class ModuloController {
    @AuraEnabled(cacheable=true)
    public static List<Treinamento_Modulo__c> getModuloAtivoRelacionado(string Id,
                                                                        string TreinamentoId,
                                                                        string Name,
                                                                        string Descricao,
                                                                        string Ativo){
        List<Treinamento_Modulo__c> objReturn = new List<Treinamento_Modulo__c>();

        string strWhere = '';        
        // Carrega a query de resultado
        string strQuery = getRegularQuery();
        // Converte o filtro de modo a utilizar como objeto
        String strFiltro = setJsonFilter(Id, TreinamentoId, Name, Descricao, Ativo);
        // Remove possiveis injections e converte em objeto
        FiltroModulo objFilter = removeInjectionAndConvert(strFiltro);
        // Atribui os filtros recebidos
        strWhere = getFiltroModulo(objFilter,true);
        // Verifica se tem alguma condição no where
        strQuery +=  (strWhere !='') ? strWhere : '';
        strQuery +=' ORDER BY ModuloId__r.Name ';
        // Executa o método na base
        objReturn = Database.query(strQuery);
        // Retorna o resultado
        return objReturn;
    }

    @AuraEnabled(cacheable=true)
    public static List<Treinamento_Modulo__c> getModuloRelacionado(String strFiltro){
        List<Treinamento_Modulo__c> objReturn = new List<Treinamento_Modulo__c>();
        string strWhere = '';        
        string strQuery = getRegularQuery();

        // Remove possiveis injections e converte em objeto
        FiltroModulo objFilter = removeInjectionAndConvert(strFiltro);
        // Atribui os filtros recebidos
        strWhere = getFiltroModulo(objFilter,false);
        system.debug('strWhere >>>> ' + strWhere) ;

        // Verifica se tem alguma condição no where
        strQuery +=  (strWhere !='') ? strWhere : '';
        strQuery +=' ORDER BY ModuloId__r.Name ';
        System.debug('strQuery >>>>> ' + strQuery);

        // Executa o método na base
        objReturn = Database.query(strQuery);
        // Retorna o resultado
        return objReturn;
    }

    private static FiltroModulo removeInjectionAndConvert (String objFilter){
        String jsonString = String.escapeSingleQuotes(objFilter);
        return (FiltroModulo)JSON.deserializeStrict(jsonString, FiltroModulo.class);
    }   

    private static string getFiltroModulo(FiltroModulo objFilter, Boolean blnAtivo){
        string strRetorno ='';
        // Verifica se os campos estão preenchidos
        if (objFilter.Id != null && objFilter.Id !=''){
            strRetorno += 'ModuloId__r.ID = \'' + objFilter.Id + '\' ';
        }
        if (objFilter.Name != null && objFilter.Name !=''){
            strRetorno += (strRetorno=='') ? 'ModuloId__r.Name LIKE \'%' + objFilter.Name + '%\' ' : 'AND ModuloId__r.Name LIKE \'%' + objFilter.Name + '%\' ' ; 
        }

        if (objFilter.Name != null && objFilter.TreinamentoId !=''){
            strRetorno += (strRetorno=='') ? 'TreinamentoId__c = \'' + objFilter.TreinamentoId + '\' ' : 'AND TreinamentoId__c = \'' + objFilter.TreinamentoId + '\' ' ; 
        }

        if (objFilter.Descricao != null && objFilter.Descricao !=''){
            strRetorno += (strRetorno=='') ? 'ModuloId__r.Descricao__c LIKE \'%' + objFilter.Descricao + '%\' ' : 'AND ModuloId__r.Descricao__c LIKE \'%' + objFilter.Descricao + '%\' ' ; 
        }

        if (blnAtivo){
            strRetorno += (strRetorno=='') ? 'ModuloId__r.Ativo__c = ' +  String.valueof(blnAtivo)  + ' ' : 'AND ModuloId__r.Ativo__c = ' + String.valueof(blnAtivo) + ' ' ; 
        }else{
            if (objFilter.Name != null && objFilter.Name !=''){
                strRetorno += (strRetorno=='') ? 'ModuloId__r.Ativo__c = ' + objFilter.Ativo + ' ' : 'AND ModuloId__r.Ativo__c = ' + objFilter.Ativo  + ' ' ; 
            }
        }

        strRetorno = (strRetorno != '') ? 'WHERE ' + strRetorno : '';

        return strRetorno ;
    }

    private static string getRegularQuery(){
        string strQuery = 'SELECT ModuloId__r.ID, ModuloId__r.Name, TreinamentoId__c,  ';
        strQuery += 'ModuloId__r.Descricao__c, ModuloId__r.Ativo__c  ';
        strQuery += 'FROM Treinamento_Modulo__c ';
        return strQuery;
    }

    private static string setJsonFilter(string Id,
                                        string TreinamentoId,
                                        string Name,
                                        string Descricao,
                                        string Ativo){

        FiltroModulo objFilter = new FiltroModulo();
        objFilter.id = id;
        objFilter.TreinamentoId = TreinamentoId;
        objFilter.Name = Name;
        objFilter.Descricao = Descricao;
        objFilter.Ativo = Ativo;

        return JSON.serialize(objFilter);
    }


}