Deploy/objects/Treinamento_Modulo__c.object
<CustomObject>
    <description>Treinamentos e Modulos</description>
    <gender/>
    <label>Treinamento Modulo</label>
    <nameField>
        <displayFormat>trm-{00000}</displayFormat>
        <label>Treinamento Modulo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Treinamento Modulos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <fields>
        <fullName>ModuloId__c</fullName>
        <description>Modulo</description>
        <inlineHelpText>Defina o módulo a ser vinculado</inlineHelpText>
        <label>Modulo</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Modulo__c.Ativo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Modulo__c</referenceTo>
        <relationshipLabel>Treinamento Modulos</relationshipLabel>
        <relationshipName>Treinamento_Modulos</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TreinamentoId__c</fullName>
        <description>Treinamento</description>
        <inlineHelpText>Defina o treinamento a ser vinculado</inlineHelpText>
        <label>Treinamento</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Treinamento__c.Ativo__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Treinamento__c</referenceTo>
        <relationshipLabel>Treinamento Modulos</relationshipLabel>
        <relationshipName>Treinamento_Modulos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

Deploy/classes/TreinamentoModuloHelperClass.cls
public with sharing class TreinamentoModuloHelperClass {
   /**************************************************************************
    * Método   : getTreinamentoModuloCadastrado
    * Objetivo : Verificar se existe um item cadastrado antes da inclusão
    * Entradas : List<Treinamento_Modulo__c> objTreina
    * Saídas   : True/False
    * Data     : 04/03/2020
    * Autor    : Charleston Santos
    *------------------------------------------------------------------------
    * Alteração: dd/mm/aaaa
    * Autor    : 
    * Motivo   :
    **************************************************************************/
    public static Boolean getTreinamentoModuloCadastrado(List<Treinamento_Modulo__c> objTreina){
        Boolean blnReturn = false;
        Set<String> strTreinamento = new Set<String>();
        Set<String> strModulo= new Set<String>();

        // Verifica todos os Ids de treinamento e modulo
        for(Treinamento_Modulo__c objRow: objTreina){
            strTreinamento.add(objRow.TreinamentoId__c);
            strModulo.add(objRow.ModuloId__c);
        }

        // Verifica se na base já existe o treinnamento é o modulo
        List<Treinamento_Modulo__c> objCheck = [SELECT ID FROM Treinamento_Modulo__c
                                                WHERE TreinamentoId__c IN :strTreinamento
                                                AND   ModuloId__c IN :strModulo];
        // Se existir, retorna true
        if(objCheck.size()>0){
            blnReturn=true;
        }
        return blnReturn;
    }
}